cache:
  mount:
    - .git
build:
  image: docker
  privileged: true 
  commands:
    - docker -d
    - docker version
    - docker build --tag=node-test .
    - docker images
      
# publish:
#   docker:
#     when:
#       branch: master
#       event: push
#     registry: $$DOCKER_LOCAL
#     username: $$DOCKER_USER
#     password: $$DOCKER_PASS
#     email: $$DOCKER_EMAIL
#     repo: vc-portal/node
#     insecure: true
#     force_tag: true
#     tag:
#       - latest
#       - "$$BUILD_NUMBER"
#     file: Dockerfile
#     load: .docker-cache/node-image.tar
#     save:
#       destination: .docker-cache/node-image.tar
      